### ISSUE TITLE
Data Series does not plot

### ISSUE THREAD

**Issue by marioharper182** [Castronova/EMIT#132] opened 2015-05-08 16:40 UTC
Any database object will not plot

**Comment by marioharper182** [comment] 2015-05-13 16:54
On right click context for the database elements, the plot does not come up and the application freezes.

**Comment by Castronova** [comment] 2015-05-13 17:30
This is because of a recent commit that I made to standardize spatial 
plotting.  To fix this, the database plotting needs to be refactored.

> Mario Harper <mailto:notifications@github.com>
> May 13, 2015 at 10:54 AM
>
> On right click context for the database elements, the plot does not 
> come up and the application freezes.
>
> —
> Reply to this email directly or view it on GitHub 
> <https://github.com/Castronova/EMIT/issues/132#issuecomment-101745504>.
>
> Mario Harper <mailto:notifications@github.com>
> May 8, 2015 at 10:40 AM
>
> Any database object will not plot
>
> —
> Reply to this email directly or view it on GitHub 
> <https://github.com/Castronova/EMIT/issues/132>.
>

-- 
Anthony Castronova
Research Assistant Professor
Utah Water Research Laboratory
Utah State University

**Comment by farrieta9** [comment] 2015-05-20 17:42
When loading a simulations and trying to plot it the database['session'] is missing.

**Comment by Castronova** [comment] 2015-05-20 21:08
**Timeseries** plotting has been fixed, but **Simulation** plotting still does not work.

**Comment by Castronova** [comment] 2015-05-21 15:12
This should be fixed now.

**Comment by Castronova** [comment] 2015-05-21 15:21
@marioharper182  please test this for me and close it if the issue is addressed

**Comment by Castronova** [comment] 2015-05-28 15:52
Not working: `SetColumnWidth(): invalid column index`

**Closed** 2015-07-21 18:08 UTC
Labels: bug
